import sqlite3, os
db = os.path.join(os.path.dirname(__file__), '..', 'data', 'okf', 'knowledge.db')
conn = sqlite3.connect(db)
c = conn.cursor()
print('=== OKF DB Stats ===')
c.execute('SELECT COUNT(*) FROM okf_nodes'); print(f'Total nodes: {c.fetchone()[0]}')
c.execute('SELECT subject, COUNT(*) FROM okf_nodes GROUP BY subject')
for r in c.fetchall(): print(f'  {r[0]}: {r[1]}')
c.execute('SELECT COUNT(*) FROM okf_edges'); print(f'Total edges: {c.fetchone()[0]}')
c.execute('SELECT edge_type, COUNT(*) FROM okf_edges GROUP BY edge_type')
for r in c.fetchall(): print(f'  {r[0]}: {r[1]}')
c.execute('SELECT COUNT(*) FROM okf_exam_traps'); print(f'Total exam traps: {c.fetchone()[0]}')
c.execute('SELECT COUNT(*) FROM okf_formulas'); print(f'Total formulas: {c.fetchone()[0]}')
c.execute('SELECT COUNT(*) FROM okf_quantities'); print(f'Total quantities: {c.fetchone()[0]}')
c.execute('SELECT COUNT(*) FROM ocr_confusions'); print(f'OCR confusions: {c.fetchone()[0]}')
print()
print('=== Sample Related Edges ===')
c.execute("SELECT from_id, to_id FROM okf_edges WHERE edge_type='related' LIMIT 6")
for r in c.fetchall(): print(f'  {r[0]}  -->  {r[1]}')
print()
print('=== Sample Node IDs (first 12) ===')
c.execute('SELECT id, subject FROM okf_nodes ORDER BY id LIMIT 12')
for r in c.fetchall(): print(f'  {r[0]} [{r[1]}]')
conn.close()
